modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="unholy_shape"
version="1.0.0"
displayName="Waxed Lightly Weathered Cut Copper Tricontadihedron"
displayURL="https://mcreator.net"
credits="Made in one hour with mcreator."
authors="ShiftyWuzHere"
description="random mod i made cause i was bored,."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.unholy_shape]]
    modId="neoforge"
    type="required"
    versionRange="[26.2.0.59,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.unholy_shape]]
    modId="minecraft"
    type="required"
    versionRange="[26.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration